In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.0


# 1. NumPy creating arrays

# creating an Numpy ndarray object by using array() function

In [3]:
array=np.array([1,2,3,4,5])
print(array)
print(type(array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# using tuple to create the array

In [4]:
array=np.array((1,2,3,4,5))
print(array)
print(type(array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# Dimensions in arrays

In [5]:
# 0-D arrays
array=np.array(10)
print(array)

10


In [6]:
# 1-D arrays
array=np.array([1,2,3,4,5])
print(array)


[1 2 3 4 5]


In [9]:
# 2-D arrays
array=np.array([[1,2,3],[4,5,6]])
print(array)

[[1 2 3]
 [4 5 6]]


In [11]:
# 3-D arrays
array=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(array)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# checking number of dimensions
- we have ndim attribute that returns the integer that tells us how many dimensions the array have

In [12]:
a = np.array(10)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = array=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Higher dimension arrays

In [14]:
array=np.array([1,2,3,4],ndmin=5)
print(array)
print(array.ndim)

[[[[[1 2 3 4]]]]]
5


# 2. NumPy Array indexing

In [17]:
b = np.array([1,2,3,4,5])
# get elemrnt at particular index
print(b[1])
# get element and add them 
print(b[1]+b[2])

2
5


# 2-D Arrays

In [20]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1, 0])


6


# 3-D arrays


In [21]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[1,1,0])

10


# Negative indexing

In [22]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1,-1])

10


# 3. NumPy array slicing

In [28]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
# determine the step
print(arr[1:5:2])
print(arr[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


# slicing 2-D arrays

In [31]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


# 4. NumPy DataTypes
- These are the datatypes in python
- strings
- integer
- float
- boolean
- complex

- NumPy has some extra data types, and refer to data types with one character.
- Below is a list of all data types in NumPy and the characters used to represent them.
1. i - integer
2. b - boolean
3. u - unsigned integer
4. f - float
5. c - complex float
6. m - timedelta
7. M - datetime
8. O - object
9. S - string
10. U - unicode string
11. V - fixed chunk of memory for other type ( void )

In [32]:
# to check the datatype of the arrays
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


In [33]:
# creating an array with defined datatype
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [34]:
# creating an array with data type 4bytes integer
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


# converting DataTypes

In [37]:
arr = np.array([1.1, 2.1, 3.1])
# using int
newarr = arr.astype(int)
# using 'i'
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [38]:
# integer to boolean
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


# 5. Numpy Copy vs View

In [42]:
arr = np.array([1, 2, 3, 4, 5])
x=arr.copy()
# making changes in the copy wont effect original and viceversa
arr[0]=4
print(arr)
print(x)

[4 2 3 4 5]
[1 2 3 4 5]


In [44]:
arr = np.array([1, 2, 3, 4, 5])
# making changes in any of the arrays effect both
x = arr.view()
arr[0] = 4
x[1]=5
print(arr)
print(x)

[4 5 3 4 5]
[4 5 3 4 5]


- so it is told that copies own the data and view doesnot own the data.
- to check this , we use the attribute base that returns 'none' if the array owns the data otherwise the base attribute refers to the original object.

In [45]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


# 6. NumPy Array shape

In [2]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [3]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


# 7. NumPy Reshaping arrays

In [4]:
# Reshape from 1-D to 2-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
# Reshape from 1-D to 3-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [6]:
# what to you think ,whether the returned array is a copy or a view
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


# Unknown Dimension
- you do not have to specify an exact number for one of the dimensions in the reshape method.
- Pass -1 as the value, and NumPy will calculate this number for you.

In [9]:
np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2,-1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Flattening the arrays

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [14]:
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2,-1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6 7 8]


# 8. Numpy Array Iterating

In [3]:
import numpy as np
arr=np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [4]:
# Iterating 2-D arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [5]:
# Iterating through each scalar element in 2-D array
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [6]:
# Iterating through 3-D arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [10]:
# Iterating through each scalar elements
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


# Iterating arrays using nditer()

In [11]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [12]:
#iterating array with different datatypes
arr = np.array([1, 2, 3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [13]:
#iterating with different step size
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


# Enumerated iteration using ndenumerate()

In [14]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [15]:
#enumerate 2-D elements
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# 9. NumPy joining Array

In [17]:
arr1=arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [18]:
# Joining two 2-D arrays along rows(axis=1)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)


[[1 2 5 6]
 [3 4 7 8]]


# Joining arrays using stack functions

In [21]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [23]:
#stacking along rows using hstack
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [24]:
#stacking along columns using vstack
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [25]:
#stacking along height(depth) using dstack
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)


[[[1 4]
  [2 5]
  [3 6]]]


# 10. NumPy array split

In [28]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [29]:
#accessing splitted arrays
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [35]:
# splitting 2-D arrays
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)
print(newarr)
print(newarr[0])
print(newarr[1])
print(newarr[2])


[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


In [36]:
#spliting the 2-D arrays,but with three elements each
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [39]:
#splitting along row
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [40]:
# alternate way using hsplit()
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [41]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.vsplit(arr, 3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


# 11. NumPy searching arrays

In [43]:
# find the indexes of the values
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [44]:
#the indexes where the values are even
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [45]:
# the indexes wheere the values are odd
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 1)
print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [46]:
# we can search using the method search sorted(),which performs the binary search in the array and returns the index where the specified value would be inserted to maintain the search order
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

1


In [47]:
# search indexing from the right
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right')
print(x)

2


In [48]:
#searching more than one value
#it returns where these should be placed to maintain the order
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)

[1 2 3]


In [49]:
import numpy as np
arr = np.array([15, 38, 41, 46])
x = np.where(arr%2 == 1)
print(x)

(array([0, 2], dtype=int64),)


# 12. NumPy Sorting arrays

In [50]:
import numpy as np
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [51]:
# sorting an boolean array
import numpy as np
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


In [52]:
#sort array alphabetically
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))


['apple' 'banana' 'cherry']


In [53]:
# sorting 2-D array
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# 13. NumPy Filter Array
- In NumPy, you filter an array using a boolean index list.
- If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [54]:
#creating an array of elements from index 0 and 2 
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


In [55]:
#creating the filter array that will return the only values that are higher
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

for element in arr:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [56]:
#creating filter directly from array
import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False False  True  True]
[43 44]


In [57]:
#only even elements
import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr % 2==0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True]
[42 44]
