# 1. Simple Arthmetic

In [3]:
import numpy as np

In [4]:
# Addition
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)

[30 32 34 36 38 40]


In [2]:
# subtraction
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)

[-10  -1   8  17  26  35]


In [5]:
# multiplication
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)

print(newarr)

[ 200  420  660  920 1200 1500]


In [6]:
# Division
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.divide(arr1, arr2)

print(newarr)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


In [7]:
# power
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)

print(newarr)

[      1000    3200000  729000000 -520093696       2500          0]


In [8]:
# both the remainder and mod functions can return remainders
# mod
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


In [9]:
# remainder
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.remainder(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


In [10]:
# the divmod() function returns both the quotient and mod.
# the first array represents the quotients
# the second array represents the remainders of the same divisions
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


In [11]:
# Absolute values
arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)

[1 2 1 2 3 4]


# 2. Rounding Decimals
- five ways of rounding off decimals in NumPy
1. truncation
2. fix
3. rounding
4. floor
5. ceil

In [12]:
# Truncation
arr=np.trunc([-3.1666, 3.6667])
print(arr)

[-3.  3.]


In [13]:
# fix
arr = np.fix([-3.1666, 3.6667])
print(arr)

[-3.  3.]


In [14]:
# rounding
arr = np.around(3.1666, 2)
print(arr)

3.17


In [15]:
# floor
# rounds off decimal to nearest lowest integer
arr = np.floor([-3.1666, 3.6667])
print(arr)

[-4.  3.]


In [16]:
# ceil
# rounds off decimal to nearest highest integer
arr = np.ceil([-3.1666, 3.6667])
print(arr)

[-3.  4.]


# 3. NumPy Logs

In [18]:
# log at base 2
arr = np.arange(1, 10)
print(np.log2(arr))


[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [19]:
# log at base 10
arr = np.arange(1, 10)
print(np.log10(arr))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


In [20]:
# natural log or log at base e
arr = np.arange(1, 10)
print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [22]:
# log at any base
from math import log
nplog=np.frompyfunc(log,2,1)
print(nplog(100,15))

1.7005483074552052


# 4. NumPy summations

In [23]:
#summation
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2])

print(newarr)

12


In [24]:
# summation over axis
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=1)

print(newarr)

[6 6]


In [25]:
# cummilative sum
arr = np.array([1, 2, 3])

newarr = np.cumsum(arr)

print(newarr)

[1 3 6]


# 5. NumPy products

In [26]:
# the product of elements of an array
arr = np.array([1, 2, 3, 4])
x = np.prod(arr)
print(x)

24


In [27]:
#product of the elements of two arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
x = np.prod([arr1, arr2])
print(x)

40320


In [28]:
# product over an axis
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
newarr = np.prod([arr1, arr2], axis=1)
print(newarr)

[  24 1680]


In [29]:
# cummulative product
arr = np.array([5, 6, 7, 8])
newarr = np.cumprod(arr)
print(newarr)

[   5   30  210 1680]


# 6. NumPy Differences

In [30]:
arr = np.array([10, 15, 25, 5])
newarr = np.diff(arr)
print(newarr)

[  5  10 -20]


In [33]:
# computing the difference twice or n number of times by giving the paramater
arr = np.array([10, 15, 25, 5])
newarr = np.diff(arr,n=3)
print(newarr)

[-35]


# 7. Finding LCM
- The lowest common multiple is the smallest number that is common multiple of two numbers

In [1]:
import numpy as np
num1=4
num2=6
x=np.lcm(num1,num2)
print(x)

12


In [2]:
# finding LCM in arrays
# to find the LCM of all values of array, we can use reduce() method
arr=np.array([3,6,9])
x=np.lcm.reduce(arr)
print(x)

18


In [4]:
arr=np.arange(1,11)
x=np.lcm.reduce(arr)
print(x)

2520


# 8. Finding GCD
- The greatest common denominator , also known as Highest common Factor is the biggest number that is common factor for both of the numbers.

In [5]:
num1=6
num2=9
x=np.gcd(num1,num2)
print(x)

3


In [6]:
# finding the gcd for all the numbers in array
arr=np.array([20,8,32,36,16])
x=np.gcd.reduce(arr)
print(x)

4


# 9. Trignometric Functions

In [13]:
s=np.sin(np.pi/2)
u=np.cos(np.pi/2)
r=np.tan(np.pi/2)
print(s)
print(u)
print(r)


1.0
6.123233995736766e-17
1.633123935319537e+16


In [10]:
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x=np.sin(arr)
print(x)

[1.         0.8660254  0.70710678 0.58778525]


In [14]:
# convert degrees to radians
arr=np.array([90,180,270,360])
x=np.deg2rad(arr)
print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


In [15]:
# radians to degrees
arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])
x = np.rad2deg(arr)
print(x)


[ 90. 180. 270. 360.]


In [17]:
# finding angles
x=np.arcsin(1.0)
x=np.rad2deg(x)
print(x)

90.0


In [18]:
# angle of each values in arrays
arr=np.array([1,-1,0.1])
x=np.arcsin(arr)
x=np.rad2deg(x)
print(x)

[ 90.         -90.           5.73917048]


In [19]:
# hypotenues
base=3
perp=4
x=np.hypot(base,perp)
print(x)

5.0


# 10. Hyperbolic Functions

In [20]:
x=np.sinh(np.pi/2)
print(x)

2.3012989023072947


In [21]:
# finding values in a array
arr=np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x=np.cosh(arr)
print(x)

[2.50917848 1.60028686 1.32460909 1.20397209]


In [22]:
# finding angles
x=np.arcsinh(1.0)
print(x)

0.881373587019543


In [23]:
# angle of each value in array
arr=np.array([0.1,0.2,0.5])
x=np.arctanh(arr)
print(x)

[0.10033535 0.20273255 0.54930614]


# 11. NumPy set operations

In [24]:
# getting the set (unique elements)
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
x=np.unique(arr)
print(x)

[1 2 3 4 5 6 7]


In [26]:
# finding union
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
newarr=np.union1d(arr1,arr2)
print(newarr)

[1 2 3 4 5 6]


In [27]:
# finding intersection
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
newarr = np.intersect1d(arr1, arr2, assume_unique=True)
print(newarr)

[3 4]


In [28]:
# finding difference
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])
newarr = np.setdiff1d(set1, set2, assume_unique=True)
print(newarr)

[1 2]


In [29]:
# finding the elements that are not present in both sets
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])
newarr = np.setxor1d(set1, set2, assume_unique=True)
print(newarr)

[1 2 5 6]
